Milestone 8: integration specs for views and fix n+1 problems
abel-tefera/ror-blog-app pull request #11
Opened 2023-08-30 13:10 UTC by abel-tefera

### Summary

- Fixed the n + 1 problem by fetching post, comments and their author in one query

**Before**
![Screenshot 2023-08-29 154707](https://github.com/abel-tefera/ror-blog-app/assets/40035531/82e507b2-5d3e-460a-90d9-5cebc0739186)

**After**
![Screenshot 2023-08-29 154746](https://github.com/abel-tefera/ror-blog-app/assets/40035531/afa0011e-242a-45b6-b3d0-3f65b50f6922)

- Ran integration tests for the following pages: 

User index page:

- I can see the username of all other users.
- I can see the profile picture for each user.
- I can see the number of posts each user has written.
- When I click on a user, I am redirected to that user's show page.

User show page:

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see the user's bio.
- I can see the user's first 3 posts.
- I can see a button that lets me view all of a user's posts.
- When I click a user's post, it redirects me to that post's show page.
- When I click to see all posts, it redirects me to the user's post's index page.

User post index page:

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see a post's title.
- I can see some of the post's body.
- I can see the first comments on a post.
- I can see how many comments a post has.
- I can see how many likes a post has.
- I can see a section for pagination if there are more posts than fit on the view.
- When I click on a post, it redirects me to that post's show page.

Post show page:

- I can see the post's title.
- I can see who wrote the post.
- I can see how many comments it has.
- I can see how many likes it has.
- I can see the post body.
- I can see the username of each commentor.
- I can see the comment each commentor left.

2023-08-30 13:33 UTC, julie-ify requested changes
## Hi @abel-tefera and @Tshobohwa,

Good job so far!

## Highlights!
- Removal of N+1 query problem
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 13:33 UTC, julie-ify commented on test/system/post_index_spec.rb
> +
- [ ] **[OPTIONAL]** I think this folder should be in the `spec/` folder where you have other spec files, instead of `test/`

2023-08-30 13:33 UTC, julie-ify commented on test/system/post_show_spec.rb
> +  comment = Comment.create(user_id: user.id, post_id: post.id, text: 'text')
- [ ] Your tests in this file failed to run because you are trying to create a comment with `user_id`, instead of `author_id`

2023-08-30 13:33 UTC, julie-ify commented on test/system/post_index_spec.rb
> +  Comment.create(user_id: commenter.id, post_id: first_post.id, text: 'another comment')
- [ ] Kindly create the comment with `author_id`, instead of `user_id`.

2023-08-30 13:33 UTC, julie-ify commented on test/system/post_index_spec.rb
> +          expect(page).to have_content("#{comment.author.name}: #{comment.text}")
- [ ] This test and some others are failing. Kindly fix them.

  ![image](https://github.com/abel-tefera/ror-blog-app/assets/81468675/6edb04f1-24db-41aa-8235-bd5c320da3a7)

2023-08-30 14:13 UTC, BregornOriginal requested changes
Hi @abel-tefera  

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good Pull Request description

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 14:13 UTC, BregornOriginal commented on spec/system/post_index_spec.rb
> +RSpec.describe 'Post index page', type: :feature do
- [ ] Kindly, as was requested by the previous reviewer. Fix the tests that are failing.

![image](https://github.com/abel-tefera/ror-blog-app/assets/93630700/a2f10015-77ed-4dd9-8189-24e5855d8c63)

2023-08-31 08:21 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @abel-tefera, @Tshobohwa 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following Requirements
✔️ Great work on organizing your tests well 👍
✔️ Great work on testing the app very well 🔥

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval. Still, we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 08:21 UTC, HAMMAS-SALEEM commented on app/assets/stylesheets/application.css
>  }
**[OPTIONAL BUT HIGHLY RECOMMENDED]**

- [ ] It would be nice if you make your own logo of your name and put that in the readme file at the top to present yourself as a brand in the job market or tech industry to catch the recruiters' eyes 👍

2023-08-31 08:37 UTC, merged